/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        outline: "#747878",
        "surface-container-high": "#ebe7e6",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#1c1b1a",
        "on-error": "#ffffff",
        "outline-variant": "#c4c7c7",
        "surface-bright": "#fdf8f8",
        background: "#fdf8f8",
        "on-surface": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#454747",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#484645",
        "primary-fixed": "#e5e2e1",
        "on-secondary": "#ffffff",
        "on-primary-container": "#858383",
        "on-secondary-container": "#5f6161",
        "inverse-surface": "#313030",
        "on-tertiary-fixed": "#1c1b1a",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "primary-container": "#1c1b1b",
        primary: "#000000",
        "on-secondary-fixed": "#1a1c1c",
        "on-surface-variant": "#444748",
        "on-tertiary-container": "#868382",
        "inverse-on-surface": "#f4f0ef",
        "error-container": "#ffdad6",
        surface: "#fdf8f8",
        "surface-tint": "#5f5e5e",
        "surface-container-low": "#f7f3f2",
        "on-background": "#1c1b1b",
        "on-primary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "secondary-container": "#dcdddd",
        error: "#ba1a1a",
        "surface-dim": "#ddd9d8",
        "primary-fixed-dim": "#c8c6c5",
        "tertiary-fixed-dim": "#cac6c4",
        secondary: "#5d5f5f",
        "tertiary-fixed": "#e6e2df",
        tertiary: "#000000",
        "surface-container": "#f1edec",
        "inverse-primary": "#c8c6c5",
        "secondary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        unit: "8px",
        "margin-desktop": "64px",
        gutter: "24px",
        "container-max": "1280px",
        "section-gap": "128px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        display: ["Inter"],
        "label-mono": ["JetBrains Mono"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        caption: ["Inter"],
      },
      fontSize: {
        "body-lg": [
          "18px",
          {
            lineHeight: "1.6",
            letterSpacing: "0",
            fontWeight: "400",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "1.6",
            letterSpacing: "0",
            fontWeight: "400",
          },
        ],
        display: [
          "72px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.04em",
            fontWeight: "800",
          },
        ],
        "label-mono": [
          "14px",
          {
            lineHeight: "1.4",
            letterSpacing: "0.05em",
            fontWeight: "500",
          },
        ],
        "headline-lg-mobile": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "48px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "1.4",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        caption: [
          "12px",
          {
            lineHeight: "1.4",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  plugins: [],
};
