# Generated by Django 6.0.6 on 2026-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('skillCategory', models.CharField(default='Frontend', max_length=100)),
                ('skills', models.TextField(blank=True, default='')),
                ('projectTitle', models.CharField(blank=True, default='', max_length=255)),
                ('projectDescription', models.TextField(blank=True, default='')),
                ('projectTech', models.CharField(blank=True, default='', max_length=255)),
                ('projectUrl', models.URLField(blank=True, default='')),
                ('projectImage', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('certificationTitle', models.CharField(blank=True, default='', max_length=255)),
                ('certificateName', models.CharField(blank=True, default='', max_length=255)),
                ('certificateFrom', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
