# Generated by Django 6.0.6 on 2026-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_aimlskills_profile_backendskills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='databaseSkills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='otherSkills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
