# Generated by Django 6.0.6 on 2026-06-30 11:33

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projectimage_profile_certificate_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.FileField(blank=True, null=True, upload_to=portfolio.models.upload_profile_pic),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=portfolio.models.upload_resume),
        ),
    ]
